-- Excluir sequência.

DROP SEQUENCE SQ_DV_REGIAO;

DROP SEQUENCE SQ_DV_ESTADO;

DROP SEQUENCE SQ_DV_CIDADE;

DROP SEQUENCE SQ_DV_BAIRRO;

DROP SEQUENCE SQ_DV_LOGRADOURO;

DROP SEQUENCE SQ_DV_EXAME;

DROP SEQUENCE SQ_DV_CONSULTA;

DROP SEQUENCE SQ_DV_DIAGNOSTICO_EXAME;

DROP SEQUENCE SQ_DV_CELULAR;

DROP SEQUENCE SQ_DV_MENSAGEM;

DROP SEQUENCE SQ_DV_PACIENTE;

DROP SEQUENCE SQ_DV_EMAIL;

DROP SEQUENCE SQ_DV_DIAGNOSTICO_CONSULTA;

DROP SEQUENCE SQ_DV_PACIENTE_REMEDIO;

DROP SEQUENCE SQ_DV_PACIENTE_DOENCA;

DROP SEQUENCE SQ_DV_DOENCA;

DROP SEQUENCE SQ_DV_REMEDIO;

DROP SEQUENCE SQ_DV_SINTOMA;

-- Criar sequências.

CREATE SEQUENCE SQ_DV_REGIAO START WITH 1;

CREATE SEQUENCE SQ_DV_ESTADO START WITH 1;

CREATE SEQUENCE SQ_DV_CIDADE START WITH 1;

CREATE SEQUENCE SQ_DV_BAIRRO START WITH 1;

CREATE SEQUENCE SQ_DV_LOGRADOURO START WITH 1;

CREATE SEQUENCE SQ_DV_EXAME START WITH 1;

CREATE SEQUENCE SQ_DV_CONSULTA START WITH 1;

CREATE SEQUENCE SQ_DV_DIAGNOSTICO_EXAME START WITH 1;

CREATE SEQUENCE SQ_DV_CELULAR START WITH 1;

CREATE SEQUENCE SQ_DV_MENSAGEM START WITH 1;

CREATE SEQUENCE SQ_DV_PACIENTE START WITH 1;

CREATE SEQUENCE SQ_DV_EMAIL START WITH 1;

CREATE SEQUENCE SQ_DV_DIAGNOSTICO_CONSULTA START WITH 1;

CREATE SEQUENCE SQ_DV_PACIENTE_REMEDIO START WITH 1;

CREATE SEQUENCE SQ_DV_PACIENTE_DOENCA START WITH 1;

CREATE SEQUENCE SQ_DV_DOENCA START WITH 1;

CREATE SEQUENCE SQ_DV_REMEDIO START WITH 1;

CREATE SEQUENCE SQ_DV_SINTOMA START WITH 1;

-- Exlcuir tabelas.

DROP TABLE T_DV_REGIAO CASCADE CONSTRAINTS;

DROP TABLE T_DV_ESTADO CASCADE CONSTRAINTS;

DROP TABLE T_DV_REMEDIO CASCADE CONSTRAINTS;

DROP TABLE T_DV_SINTOMA CASCADE CONSTRAINTS;

DROP TABLE T_DV_DOENCA_SINTOMA CASCADE CONSTRAINTS;

DROP TABLE T_DV_CIDADE CASCADE CONSTRAINTS;

DROP TABLE T_DV_BAIRRO CASCADE CONSTRAINTS;

DROP TABLE T_DV_PACIENTE_REMEDIO CASCADE CONSTRAINTS;

DROP TABLE T_DV_PACIENTE_DOENCA CASCADE CONSTRAINTS;

DROP TABLE T_DV_DOENCA CASCADE CONSTRAINTS;

DROP TABLE T_DV_LOGRADOURO CASCADE CONSTRAINTS;

DROP TABLE T_DV_ENDERECO_PACIENTE CASCADE CONSTRAINTS;

DROP TABLE T_DV_PACIENTE CASCADE CONSTRAINTS;

DROP TABLE T_DV_EMAIL CASCADE CONSTRAINTS;

DROP TABLE T_DV_DIAGNOSTICO_CONSULTA CASCADE CONSTRAINTS;

DROP TABLE T_DV_ENDERECO_EXAME CASCADE CONSTRAINTS;

DROP TABLE T_DV_CELULAR CASCADE CONSTRAINTS;

DROP TABLE T_DV_MENSAGEM CASCADE CONSTRAINTS;

DROP TABLE T_DV_EXAME CASCADE CONSTRAINTS;

DROP TABLE T_DV_CONSULTA CASCADE CONSTRAINTS;

DROP TABLE T_DV_DIAGNOSTICO_EXAME CASCADE CONSTRAINTS;

-- Criar tabelas.

CREATE TABLE T_DV_BAIRRO (
    ID_BAIRRO NUMBER(6) DEFAULT SQ_DV_BAIRRO.NEXTVAL NOT NULL,
    ID_CIDADE NUMBER(4) NOT NULL,
    NM_BAIRRO VARCHAR2(80) NOT NULL
);

COMMENT ON TABLE T_DV_BAIRRO IS
    'Esta tabela representa os bairros brasileiros.';

COMMENT ON COLUMN T_DV_BAIRRO.ID_BAIRRO IS
    'Chave primária da tabela bairro. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_BAIRRO.ID_CIDADE IS
    'Chave estrangeira da tabela cidade. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_BAIRRO.NM_BAIRRO IS
    'Este atributo representa o nome de um bairro brasileiro.';

ALTER TABLE T_DV_BAIRRO ADD CONSTRAINT PK_DV_BAIRRO PRIMARY KEY ( ID_BAIRRO );

CREATE TABLE T_DV_CELULAR (
    ID_TELEFONE NUMBER(10) DEFAULT SQ_DV_CELULAR.NEXTVAL NOT NULL,
    ID_PACIENTE NUMBER(9) NOT NULL,
    NR_TELEFONE VARCHAR2(15) NOT NULL
);

COMMENT ON TABLE T_DV_CELULAR IS
    'Esta tabela representa o celular do paciente.';

COMMENT ON COLUMN T_DV_CELULAR.ID_TELEFONE IS
    'Chave primária da tabela telefone. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_CELULAR.ID_PACIENTE IS
    'Chave estrangeira da tabela paciente. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_CELULAR.NR_TELEFONE IS
    'Este atributo armazena o número de telefone do paciente. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_CELULAR ADD CONSTRAINT PK_DV_CELULAR PRIMARY KEY ( ID_TELEFONE );

CREATE TABLE T_DV_CIDADE (
    ID_CIDADE NUMBER(4) DEFAULT SQ_DV_CIDADE.NEXTVAL NOT NULL,
    CD_ESTADO NUMBER(2) NOT NULL,
    NM_CIDADE VARCHAR2(50) NOT NULL
);

COMMENT ON TABLE T_DV_CIDADE IS
    'Esta tabela representa as cidades brasileiras.';

COMMENT ON COLUMN T_DV_CIDADE.ID_CIDADE IS
    'Chave primária da tabela de cidades brasileiras. Sua sequência é simples.';

COMMENT ON COLUMN T_DV_CIDADE.CD_ESTADO IS
    'Chave estrangeira da tabela estado. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_CIDADE.NM_CIDADE IS
    'Este atributo representa o nome de uma cidade brasileira. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_CIDADE ADD CONSTRAINT PK_DV_CIDADE PRIMARY KEY ( ID_CIDADE );

CREATE TABLE T_DV_CONSULTA (
    ID_CONSULTA NUMBER(18) DEFAULT SQ_DV_CONSULTA.NEXTVAL NOT NULL,
    ID_PACIENTE NUMBER(9) NOT NULL,
    DT_HR_CONSULTA_COMECO DATE NOT NULL,
    DT_HR_CONSULTA_FIM DATE NOT NULL,
    NR_TEMPERATURA NUMBER(3) NOT NULL,
    NR_PRESSAO VARCHAR2(5) NOT NULL
);

COMMENT ON TABLE T_DV_CONSULTA IS
    'Esta tabela representa as consultas feitas pelo paciente.';

COMMENT ON COLUMN T_DV_CONSULTA.ID_CONSULTA IS
    'Chave primária da tabela consulta. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_CONSULTA.ID_PACIENTE IS
    'Chave estrangeira da tabela paciente. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_CONSULTA.DT_HR_CONSULTA_COMECO IS
    'Este atributo armazena a data e o horário em que ocorreu o início da consulta. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_CONSULTA.DT_HR_CONSULTA_FIM IS
    'Este atributo armazena a data e o horário do final da consulta. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_CONSULTA.NR_TEMPERATURA IS
    'Este atributo armazena a temperatura corporal do paciente. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_CONSULTA.NR_PRESSAO IS
    'Este atributo armazena a pressão do paciente. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_CONSULTA ADD CONSTRAINT PK_DV_CONSULTA PRIMARY KEY ( ID_CONSULTA );

CREATE TABLE T_DV_DIAGNOSTICO_CONSULTA (
    ID_DIAGNOSTICO_CONSULTA NUMBER(15) DEFAULT SQ_DV_DIAGNOSTICO_CONSULTA.NEXTVAL NOT NULL,
    ID_DOENCA NUMBER(5),
    ID_CONSULTA NUMBER(18) NOT NULL,
    FL_DOENCA CHAR(1) NOT NULL,
    DS_DIAGNOSTICO VARCHAR2(300)
);

ALTER TABLE T_DV_DIAGNOSTICO_CONSULTA ADD CHECK ( FL_DOENCA IN ( 'N', 'S' ) );

COMMENT ON TABLE T_DV_DIAGNOSTICO_CONSULTA IS
    'Esta tabela representa o diagnóstico feito em nível de consulta.';

COMMENT ON COLUMN T_DV_DIAGNOSTICO_CONSULTA.ID_DOENCA IS
    'Chave estrangeira da tabela doença. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_DIAGNOSTICO_CONSULTA.FL_DOENCA IS
    'Este informa se o paciente possui ou não uma doença. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_DIAGNOSTICO_CONSULTA.DS_DIAGNOSTICO IS
    'Este atributo descreve o diagnóstico da doença. Seu conteúdo é opcional.';

ALTER TABLE T_DV_DIAGNOSTICO_CONSULTA ADD CONSTRAINT PK_DV_DIAGNOSTICO_CONSULTA PRIMARY KEY ( ID_DIAGNOSTICO_CONSULTA );

CREATE TABLE T_DV_DIAGNOSTICO_EXAME (
    ID_DIAGNOSTICO_EXAME NUMBER(9) DEFAULT SQ_DV_DIAGNOSTICO_EXAME.NEXTVAL NOT NULL,
    ID_EXAME NUMBER(12) NOT NULL,
    ID_DOENCA NUMBER(5),
    FL_DOENCA CHAR(1) NOT NULL,
    DS_DIAGNOSTICO VARCHAR2(300)
);

ALTER TABLE T_DV_DIAGNOSTICO_EXAME ADD CHECK ( FL_DOENCA IN ( '', 'N', 'S' ) );

COMMENT ON TABLE T_DV_DIAGNOSTICO_EXAME IS
    'Esta tabela representa o diagnóstico feito a nível de exame.';

COMMENT ON COLUMN T_DV_DIAGNOSTICO_EXAME.ID_DIAGNOSTICO_EXAME IS
    'Chave primária da tabela do diagnóstico do exame. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_DIAGNOSTICO_EXAME.ID_EXAME IS
    'Chave estrangeira da tabela exame. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_DIAGNOSTICO_EXAME.ID_DOENCA IS
    'Chave estrangeira da tabela doença. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_DIAGNOSTICO_EXAME.FL_DOENCA IS
    'Este atributo informa se foi identificado uma doença no exame. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_DIAGNOSTICO_EXAME.DS_DIAGNOSTICO IS
    'Este atributo armazena uma descrição do diagnóstico. Seu conteúdo é opcional.';

ALTER TABLE T_DV_DIAGNOSTICO_EXAME ADD CONSTRAINT PK_DV_DIAGNOSTICO_EXAME PRIMARY KEY ( ID_DIAGNOSTICO_EXAME );

CREATE TABLE T_DV_DOENCA (
    ID_DOENCA NUMBER(5) DEFAULT SQ_DV_DOENCA.NEXTVAL NOT NULL,
    NM_DOENCA VARCHAR2(100) NOT NULL
);

COMMENT ON TABLE T_DV_DOENCA IS
    'Esta tabela armazena diversas doenças, que servem tanto para informar enfermidades já possuídas pelos pacientes quanto para novos diagnósticos.';

COMMENT ON COLUMN T_DV_DOENCA.ID_DOENCA IS
    'Chave primária da tabela doença. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_DOENCA.NM_DOENCA IS
    'Este atributo representa um nome de doença. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_DOENCA ADD CONSTRAINT PK_DV_DOENCA PRIMARY KEY ( ID_DOENCA );

CREATE TABLE T_DV_DOENCA_SINTOMA (
    ID_DOENCA NUMBER(5) NOT NULL,
    ID_SINTOMA NUMBER(6) NOT NULL
);

COMMENT ON TABLE T_DV_DOENCA_SINTOMA IS
    'Tabela associativa de doença e sintoma.';

COMMENT ON COLUMN T_DV_DOENCA_SINTOMA.ID_DOENCA IS
    'Chave primária e estrangeira da tabela doença.';

COMMENT ON COLUMN T_DV_DOENCA_SINTOMA.ID_SINTOMA IS
    'Chave primária e estrangeira da tabela sintoma.';

ALTER TABLE T_DV_DOENCA_SINTOMA ADD CONSTRAINT PK_DV_DOENCA_SINTOMA PRIMARY KEY ( ID_DOENCA, ID_SINTOMA );

CREATE TABLE T_DV_EMAIL (
    ID_EMAIL NUMBER(10) DEFAULT SQ_DV_EMAIL.NEXTVAL NOT NULL,
    ID_PACIENTE NUMBER(9) NOT NULL,
    NM_EMAIL VARCHAR2(100) NOT NULL
);

COMMENT ON TABLE T_DV_EMAIL IS
    'Este atributo representa o e-mail do paciente.';

COMMENT ON COLUMN T_DV_EMAIL.ID_EMAIL IS
    'Chave primária da tabela de e-mail. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_EMAIL.ID_PACIENTE IS
    'Chave estrangeira da tabela paciente. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_EMAIL.NM_EMAIL IS
    'Este atributo armazena o e-mail do paciente. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_EMAIL ADD CONSTRAINT PK_DV_EMAIL PRIMARY KEY ( ID_EMAIL );

CREATE TABLE T_DV_ENDERECO_EXAME (
    ID_LOGRADOURO NUMBER(7) NOT NULL,
    ID_EXAME NUMBER(12) NOT NULL,
    NR_LOCAL_EXAME NUMBER(5),
    DS_COMPLEMENTO VARCHAR2(300),
    DS_PONTO_REFERENCIA VARCHAR2(300)
);

COMMENT ON TABLE T_DV_ENDERECO_EXAME IS
    'Esta tabela representa o endereço do local de exame.';

COMMENT ON COLUMN T_DV_ENDERECO_EXAME.ID_LOGRADOURO IS
    'Chave primária e estrangeira da tabela logradouro.';

COMMENT ON COLUMN T_DV_ENDERECO_EXAME.ID_EXAME IS
    'Chave primária e estrangeira da tabela exame.';

COMMENT ON COLUMN T_DV_ENDERECO_EXAME.NR_LOCAL_EXAME IS
    'Este atributo representa o número de localização do local de exame. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_ENDERECO_EXAME.DS_COMPLEMENTO IS
    'Este atributo representa o complemento da localização do local de exame. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_ENDERECO_EXAME.DS_PONTO_REFERENCIA IS
    'Este atributo representa o ponto de referência do local de exame. Seu conteúdo é opcional.';

ALTER TABLE T_DV_ENDERECO_EXAME ADD CONSTRAINT PK_DV_ENDERECO_EXAME PRIMARY KEY ( ID_LOGRADOURO, ID_EXAME );

CREATE TABLE T_DV_ENDERECO_PACIENTE (
    ID_PACIENTE NUMBER(9) NOT NULL,
    ID_LOGRADOURO NUMBER(7) NOT NULL,
    NR_RESIDENCIA NUMBER(5),
    DS_COMPLEMENTO VARCHAR2(300),
    DS_PONTO_REFERENCIA VARCHAR2(300)
);

COMMENT ON TABLE T_DV_ENDERECO_PACIENTE IS
    'Esta tabela representa os endereços do cliente.';

COMMENT ON COLUMN T_DV_ENDERECO_PACIENTE.ID_PACIENTE IS
    'Chave primária e estrangeira da tabela paciente.';

COMMENT ON COLUMN T_DV_ENDERECO_PACIENTE.ID_LOGRADOURO IS
    'Chave primária e estrangeira da tabela logradouro.';

COMMENT ON COLUMN T_DV_ENDERECO_PACIENTE.NR_RESIDENCIA IS
    'Este atributo representa o número da residência do paciente. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_ENDERECO_PACIENTE.DS_COMPLEMENTO IS
    'Este atributo representa o complemento da residência do paciente. É para informações de condomínios. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_ENDERECO_PACIENTE.DS_PONTO_REFERENCIA IS
    'Este atributo represena um ponto de referência da residência do paciente. Seu conteúdo é opcional.';

ALTER TABLE T_DV_ENDERECO_PACIENTE ADD CONSTRAINT PK_DV_ENDERECO_PACIENTE PRIMARY KEY ( ID_PACIENTE, ID_LOGRADOURO );

CREATE TABLE T_DV_ESTADO (
    CD_ESTADO NUMBER(2) DEFAULT SQ_DV_ESTADO.NEXTVAL NOT NULL,
    CD_REGIAO NUMBER(1) NOT NULL,
    SG_ESTADO VARCHAR2(2) NOT NULL,
    NM_ESTADO VARCHAR2(25) NOT NULL
);

COMMENT ON TABLE T_DV_ESTADO IS
    'Esta tabela representas os Estados brasileiros.';

COMMENT ON COLUMN T_DV_ESTADO.CD_ESTADO IS
    'Chave primária da tabela dos Estados brasileiros. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_ESTADO.CD_REGIAO IS
    'Chave estrangeira da tabela região. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_ESTADO.SG_ESTADO IS
    'Este atributo representa a sigla da unidade federativa. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_ESTADO.NM_ESTADO IS
    'Este atributo representa o nome de um Estado brasileiro. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_ESTADO ADD CONSTRAINT PK_DV_ESTADO PRIMARY KEY ( CD_ESTADO );

CREATE TABLE T_DV_EXAME (
    ID_EXAME NUMBER(12) DEFAULT SQ_DV_EXAME.NEXTVAL NOT NULL,
    ID_CONSULTA NUMBER(18) NOT NULL,
    NM_ESPECIALIDADE VARCHAR2(50) NOT NULL,
    NM_MEDICO VARCHAR2(100) NOT NULL,
    DT_EXAME DATE NOT NULL,
    HR_EXAME DATE NOT NULL
);

COMMENT ON TABLE T_DV_EXAME IS
    'Esta tabela representa o exame a ser feito pelo paciente.';

COMMENT ON COLUMN T_DV_EXAME.ID_EXAME IS
    'Chave primária da tabela exame. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_EXAME.ID_CONSULTA IS
    'Chave estrangeira da tabela consulta. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_EXAME.NM_ESPECIALIDADE IS
    'Este atributo armazena a especialidade do exame. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_EXAME.NM_MEDICO IS
    'Este atributo armazena o nome do doutor. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_EXAME.DT_EXAME IS
    'Este atributo armazena a data da realização do exame. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_EXAME.HR_EXAME IS
    'Este atributo representa o horário do exame. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_EXAME ADD CONSTRAINT PK_DV_EXAME PRIMARY KEY ( ID_EXAME );

CREATE TABLE T_DV_LOGRADOURO (
    ID_LOGRADOURO NUMBER(7) DEFAULT SQ_DV_LOGRADOURO.NEXTVAL NOT NULL,
    ID_BAIRRO NUMBER(6) NOT NULL,
    NM_LOGRADOURO VARCHAR2(80) NOT NULL,
    NR_CEP VARCHAR2(9) NOT NULL
);

COMMENT ON TABLE T_DV_LOGRADOURO IS
    'Esta tabela representa os logradouros brasileiros.';

COMMENT ON COLUMN T_DV_LOGRADOURO.ID_LOGRADOURO IS
    'Chave primária da tabela logradouro. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_LOGRADOURO.ID_BAIRRO IS
    'Chave estrangeira da tabela bairro. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_LOGRADOURO.NM_LOGRADOURO IS
    'Este atributo representa o nome de um logradouro do Brasil. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_LOGRADOURO.NR_CEP IS
    'Este atributo representa o CEP do endereço. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_LOGRADOURO ADD CONSTRAINT PK_DV_LOGRADOURO PRIMARY KEY ( ID_LOGRADOURO );

CREATE TABLE T_DV_MENSAGEM (
    ID_MENSAGEM NUMBER(21) DEFAULT SQ_DV_MENSAGEM.NEXTVAL NOT NULL,
    ID_PACIENTE NUMBER(9) NOT NULL,
    ID_CONSULTA NUMBER(18) NOT NULL,
    DT_HR_MENSAGEM DATE NOT NULL,
    TX_MENSAGEM VARCHAR2(500) NOT NULL,
    FL_PACIENTE CHAR(1) NOT NULL,
    FL_CONSULTA CHAR(1) NOT NULL
);

ALTER TABLE T_DV_MENSAGEM ADD CHECK ( FL_PACIENTE IN ( 'N', 'S' ) );

ALTER TABLE T_DV_MENSAGEM ADD CHECK ( FL_CONSULTA IN ( 'N', 'S' ) );

COMMENT ON TABLE T_DV_MENSAGEM IS
    'Esta tabela representa a mensagem mandada ou pelo paciente ou pela consulta (aplicativo).';

COMMENT ON COLUMN T_DV_MENSAGEM.ID_MENSAGEM IS
    'Chave primária da tabela mensagem. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_MENSAGEM.ID_PACIENTE IS
    'Chave e estrangeira da tabela paciente.';

COMMENT ON COLUMN T_DV_MENSAGEM.ID_CONSULTA IS
    'Chave primária e estrangeira da tabela consutla.';

COMMENT ON COLUMN T_DV_MENSAGEM.DT_HR_MENSAGEM IS
    'Este atributo armazena a data e o horário em que foi mandado a mensagem. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_MENSAGEM.TX_MENSAGEM IS
    'Este atributo armazena a mensagem trocada entre paciente e consulta e vice-versa. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_MENSAGEM.FL_PACIENTE IS
    'Este atributo indica se quem mandou a mensagem foi o paciente. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_MENSAGEM.FL_CONSULTA IS
    'Este atributo representa se quem mandou a mensagem foi o apliativo. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_MENSAGEM ADD CONSTRAINT PK_DV_MENSAGEM PRIMARY KEY ( ID_MENSAGEM );

CREATE TABLE T_DV_PACIENTE (
    ID_PACIENTE NUMBER(9) DEFAULT SQ_DV_PACIENTE.NEXTVAL NOT NULL,
    NM_PACIENTE VARCHAR2(100) NOT NULL,
    NR_CPF VARCHAR2(14) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    NM_SEXO_BIOLOGICO VARCHAR2(10),
    NM_GENERO VARCHAR2(30),
    NM_TIPO_SANGUINEO VARCHAR2(2),
    DT_INCLUSAO DATE NOT NULL,
    DT_EXCLUSAO DATE
);

ALTER TABLE T_DV_PACIENTE ADD CONSTRAINT CK_DV_SEXO_BIOLOGICO CHECK ( NM_SEXO_BIOLOGICO IN ( 'Feminino', 'Masculino' ) );

COMMENT ON TABLE T_DV_PACIENTE IS
    'Esta tabela representa os pacientes utilizadores do sistema.';

COMMENT ON COLUMN T_DV_PACIENTE.ID_PACIENTE IS
    'Chave primária da tabela paciente. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_PACIENTE.NM_PACIENTE IS
    'Este atributo representa o nome do paciente. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_PACIENTE.NR_CPF IS
    'Este atributo armazena o CPF do cliente. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_PACIENTE.DT_NASCIMENTO IS
    'Este atributo armazena a data de nascimento do cliente. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_PACIENTE.NM_SEXO_BIOLOGICO IS
    'Este atributo representa o sexo biológico do paciente, podendo ser masculino ou feminino. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_PACIENTE.NM_GENERO IS
    'Este atributo representa o gênero do paciente. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_PACIENTE.NM_TIPO_SANGUINEO IS
    'Este atributo representa o tipo sanguíneo do paciente. Seu conteúdo é opcional.';

COMMENT ON COLUMN T_DV_PACIENTE.DT_INCLUSAO IS
    'Este atributo armazena a data de inclusão do paciente no sistema. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_PACIENTE.DT_EXCLUSAO IS
    'Este atributo representa a saída do paciente do sistema. Seu conteúdo é opcional.';

ALTER TABLE T_DV_PACIENTE ADD CONSTRAINT PK_DV_PACIENTE PRIMARY KEY ( ID_PACIENTE );

ALTER TABLE T_DV_PACIENTE ADD CONSTRAINT UN_DV_PACIENTE_CPF UNIQUE ( NR_CPF );

CREATE TABLE T_DV_PACIENTE_DOENCA (
    ID_DOENCA_PACIENTE NUMBER DEFAULT SQ_DV_PACIENTE_DOENCA.NEXTVAL NOT NULL,
    ID_PACIENTE NUMBER(9),
    ID_DOENCA NUMBER(5)
);

COMMENT ON TABLE T_DV_PACIENTE_DOENCA IS
    'Tabela associativa de paciente e doença.';

COMMENT ON COLUMN T_DV_PACIENTE_DOENCA.ID_DOENCA_PACIENTE IS
    'Chave primária da tabela doença do paciente. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_PACIENTE_DOENCA.ID_PACIENTE IS
    'Chave estrangeira da tabela paciente.';

COMMENT ON COLUMN T_DV_PACIENTE_DOENCA.ID_DOENCA IS
    'Chave estrangeira da tabela doença.';

ALTER TABLE T_DV_PACIENTE_DOENCA ADD CONSTRAINT PK_DV_PACIENTE_DOENCA PRIMARY KEY ( ID_DOENCA_PACIENTE );

CREATE TABLE T_DV_PACIENTE_REMEDIO (
    ID_REMEDIO_PACIENTE NUMBER(9) DEFAULT SQ_DV_PACIENTE_REMEDIO.NEXTVAL NOT NULL,
    ID_REMEDIO NUMBER(12),
    ID_PACIENTE NUMBER(9)
);

COMMENT ON COLUMN T_DV_PACIENTE_REMEDIO.ID_REMEDIO_PACIENTE IS
    'Chave primária da tabela remédio do paciente. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_PACIENTE_REMEDIO.ID_PACIENTE IS
    'Chave estrangeira da tablea paciente.';

ALTER TABLE T_DV_PACIENTE_REMEDIO ADD CONSTRAINT PK_DV_PACIENTE_REMEDIO PRIMARY KEY ( ID_REMEDIO_PACIENTE );

CREATE TABLE T_DV_REGIAO (
    CD_REGIAO NUMBER(1) DEFAULT SQ_DV_REGIAO.NEXTVAL NOT NULL,
    NM_REGIAO VARCHAR2(15) NOT NULL
);

COMMENT ON TABLE T_DV_REGIAO IS
    'Esta tabela representa as regiões do Brasil.';

COMMENT ON COLUMN T_DV_REGIAO.CD_REGIAO IS
    'Chave primária da tabela região. Cada código representa uma das cinco regiões do Brasil: Sul, Sudeste, Centro-Oeste, Nordeste e Norte.';

COMMENT ON COLUMN T_DV_REGIAO.NM_REGIAO IS
    'Este atributo armazena o nome de uma região do Brasil. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_REGIAO ADD CONSTRAINT PK_DV_REGIAO PRIMARY KEY ( CD_REGIAO );

CREATE TABLE T_DV_REMEDIO (
    ID_REMEDIO NUMBER(12) DEFAULT SQ_DV_REMEDIO.NEXTVAL NOT NULL,
    NM_REMEDIO VARCHAR2(100) NOT NULL,
    NM_FORMA_FARMACEUTICA VARCHAR2(100) NOT NULL
);

COMMENT ON TABLE T_DV_REMEDIO IS
    'Esta tabela representa os remédios indicados e usados por pacientes.';

COMMENT ON COLUMN T_DV_REMEDIO.ID_REMEDIO IS
    'Chave primária da tabela remedio. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_REMEDIO.NM_REMEDIO IS
    'Este atributo armazena o nome do remédio. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_REMEDIO.NM_FORMA_FARMACEUTICA IS
    'Este atributo indica a forma farmaceutica do remédio (comprimido, xarope, cápsula etc.). Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_REMEDIO ADD CONSTRAINT PK_DV_REMEDIO PRIMARY KEY ( ID_REMEDIO );

CREATE TABLE T_DV_SINTOMA (
    ID_SINTOMA NUMBER(6) DEFAULT SQ_DV_SINTOMA.NEXTVAL NOT NULL,
    NM_SINTOMA VARCHAR2(100) NOT NULL,
    DS_SINTOMA VARCHAR2(300) NOT NULL
);

COMMENT ON TABLE T_DV_SINTOMA IS
    'Esta tabela representa os sistemas que uma doença pode ter.';

COMMENT ON COLUMN T_DV_SINTOMA.ID_SINTOMA IS
    'Chave primária da tabela sintoma. Sua chave é uma sequência simples.';

COMMENT ON COLUMN T_DV_SINTOMA.NM_SINTOMA IS
    'Este atributo indica o nome de um sintoma. Seu conteúdo é obrigatório.';

COMMENT ON COLUMN T_DV_SINTOMA.DS_SINTOMA IS
    'Este atributo armazena uma descrição do sintoma. Seu conteúdo é obrigatório.';

ALTER TABLE T_DV_SINTOMA ADD CONSTRAINT PK_DV_SINTOMA PRIMARY KEY ( ID_SINTOMA );

ALTER TABLE T_DV_LOGRADOURO ADD CONSTRAINT FK_DV_BAIRRO FOREIGN KEY ( ID_BAIRRO ) REFERENCES T_DV_BAIRRO ( ID_BAIRRO );

ALTER TABLE T_DV_CELULAR ADD CONSTRAINT FK_DV_CELULAR_PACIENTE FOREIGN KEY ( ID_PACIENTE ) REFERENCES T_DV_PACIENTE ( ID_PACIENTE );

ALTER TABLE T_DV_BAIRRO ADD CONSTRAINT FK_DV_CIDADE FOREIGN KEY ( ID_CIDADE ) REFERENCES T_DV_CIDADE ( ID_CIDADE );

ALTER TABLE T_DV_CONSULTA ADD CONSTRAINT FK_DV_CONSULTA_PACIENTE FOREIGN KEY ( ID_PACIENTE ) REFERENCES T_DV_PACIENTE ( ID_PACIENTE );

ALTER TABLE T_DV_DIAGNOSTICO_CONSULTA ADD CONSTRAINT FK_DV_DIAG_CONSULTA_CONSULTA FOREIGN KEY ( ID_CONSULTA ) REFERENCES T_DV_CONSULTA ( ID_CONSULTA );

ALTER TABLE T_DV_DIAGNOSTICO_CONSULTA ADD CONSTRAINT FK_DV_DIAG_CONSULTA_DOENCA FOREIGN KEY ( ID_DOENCA ) REFERENCES T_DV_DOENCA ( ID_DOENCA );

ALTER TABLE T_DV_DIAGNOSTICO_EXAME ADD CONSTRAINT FK_DV_DIAG_EXAME_DOENCA FOREIGN KEY ( ID_DOENCA ) REFERENCES T_DV_DOENCA ( ID_DOENCA );

ALTER TABLE T_DV_DIAGNOSTICO_EXAME ADD CONSTRAINT FK_DV_DIAG_EXAME_EXAME FOREIGN KEY ( ID_EXAME ) REFERENCES T_DV_EXAME ( ID_EXAME );

ALTER TABLE T_DV_DOENCA_SINTOMA ADD CONSTRAINT FK_DV_DOENCA_SINTOMA_DOENCA FOREIGN KEY ( ID_DOENCA ) REFERENCES T_DV_DOENCA ( ID_DOENCA );

ALTER TABLE T_DV_DOENCA_SINTOMA ADD CONSTRAINT FK_DV_DOENCA_SINTOMA_SINTOMA FOREIGN KEY ( ID_SINTOMA ) REFERENCES T_DV_SINTOMA ( ID_SINTOMA );

ALTER TABLE T_DV_EMAIL ADD CONSTRAINT FK_DV_EMAIL_PACIENTE FOREIGN KEY ( ID_PACIENTE ) REFERENCES T_DV_PACIENTE ( ID_PACIENTE );

ALTER TABLE T_DV_ENDERECO_EXAME ADD CONSTRAINT FK_DV_END_EXAME_EXAME FOREIGN KEY ( ID_EXAME ) REFERENCES T_DV_EXAME ( ID_EXAME );

ALTER TABLE T_DV_ENDERECO_EXAME ADD CONSTRAINT FK_DV_END_EXAME_LOGRADOURO FOREIGN KEY ( ID_LOGRADOURO ) REFERENCES T_DV_LOGRADOURO ( ID_LOGRADOURO );

ALTER TABLE T_DV_ENDERECO_PACIENTE ADD CONSTRAINT FK_DV_END_PACIENTE_LOGRADOURO FOREIGN KEY ( ID_LOGRADOURO ) REFERENCES T_DV_LOGRADOURO ( ID_LOGRADOURO );

ALTER TABLE T_DV_ENDERECO_PACIENTE ADD CONSTRAINT FK_DV_END_PACIENTE_PACIENTE FOREIGN KEY ( ID_PACIENTE ) REFERENCES T_DV_PACIENTE ( ID_PACIENTE );

ALTER TABLE T_DV_CIDADE ADD CONSTRAINT FK_DV_ESTADO FOREIGN KEY ( CD_ESTADO ) REFERENCES T_DV_ESTADO ( CD_ESTADO );

ALTER TABLE T_DV_EXAME ADD CONSTRAINT FK_DV_EXAME_CONSULTA FOREIGN KEY ( ID_CONSULTA ) REFERENCES T_DV_CONSULTA ( ID_CONSULTA );

ALTER TABLE T_DV_MENSAGEM ADD CONSTRAINT FK_DV_MENSAGEM_CONSULTA FOREIGN KEY ( ID_CONSULTA ) REFERENCES T_DV_CONSULTA ( ID_CONSULTA );

ALTER TABLE T_DV_MENSAGEM ADD CONSTRAINT FK_DV_MENSAGEM_PACIENTE FOREIGN KEY ( ID_PACIENTE ) REFERENCES T_DV_PACIENTE ( ID_PACIENTE );

ALTER TABLE T_DV_PACIENTE_DOENCA ADD CONSTRAINT FK_DV_PAC_DOENCA_DOENCA FOREIGN KEY ( ID_DOENCA ) REFERENCES T_DV_DOENCA ( ID_DOENCA );

ALTER TABLE T_DV_PACIENTE_DOENCA ADD CONSTRAINT FK_DV_PAC_DOENCA_PACIENTE FOREIGN KEY ( ID_PACIENTE ) REFERENCES T_DV_PACIENTE ( ID_PACIENTE );

ALTER TABLE T_DV_PACIENTE_REMEDIO ADD CONSTRAINT FK_DV_PAC_REMEDIO_PACIENTE FOREIGN KEY ( ID_PACIENTE ) REFERENCES T_DV_PACIENTE ( ID_PACIENTE );

ALTER TABLE T_DV_PACIENTE_REMEDIO ADD CONSTRAINT FK_DV_PAC_REMEDIO_REMEDIO FOREIGN KEY ( ID_REMEDIO ) REFERENCES T_DV_REMEDIO ( ID_REMEDIO );

ALTER TABLE T_DV_ESTADO ADD CONSTRAINT FK_DV_REGIAO FOREIGN KEY ( CD_REGIAO ) REFERENCES T_DV_REGIAO ( CD_REGIAO );