-- Incluir Região

EXECUTE INCLUIR_REGIAO('Norte');
EXECUTE INCLUIR_REGIAO('Nordeste');
EXECUTE INCLUIR_REGIAO('Centro-Oeste');
EXECUTE INCLUIR_REGIAO('Sudeste');
EXECUTE INCLUIR_REGIAO('Sul');

-- Incluir Estado

EXECUTE INCLUIR_ESTADO(1, 'AM', 'Amazonas');
EXECUTE INCLUIR_ESTADO(2, 'MA', 'Maranhão');
EXECUTE INCLUIR_ESTADO(3, 'MT', 'Mato Grosso');
EXECUTE INCLUIR_ESTADO(4, 'SP', 'São Paulo');
EXECUTE INCLUIR_ESTADO(5, 'RS', 'Rio Grande do Sul');

-- Incluir Cidade

EXECUTE INCLUIR_CIDADE(1, 'Manaus');
EXECUTE INCLUIR_CIDADE(1, 'Borba');
EXECUTE INCLUIR_CIDADE(2, 'São Luís');
EXECUTE INCLUIR_CIDADE(2, 'Caxias');
EXECUTE INCLUIR_CIDADE(3, 'Cuiabá');
EXECUTE INCLUIR_CIDADE(3, 'Rondonopólis');
EXECUTE INCLUIR_CIDADE(4, 'São Paulo');
EXECUTE INCLUIR_CIDADE(4, 'Campinas');
EXECUTE INCLUIR_CIDADE(5, 'Porto Alegre');
EXECUTE INCLUIR_CIDADE(5, 'Pelotas');

-- Incluir Bairro

EXECUTE INCLUIR_BAIRRO(1, '');